### ISSUE TITLE
RSS includes osmcha.mapbox.com

### ISSUE THREAD

**Issue by cliffordsnow** [OSMCha/osmcha-frontend#713] opened 2024-02-21 02:55 UTC
## *Brief Description*

When creating a new filter, the RSS includes ```https://osmcha.mapbox.com/api/v1/aoi/a7ea9a70-7767-444c-b0e7-bbdd6f223c91/```

## What is the motivation / use case for this feature?

I'm having trouble getting my RSS reader to read the OSMCha RSS feed

## What  is the current behaviour, (attach relevant screenshots) ?

Not showing any changesets in my area of interest, which is Washington State, US

## What  is the expected behaviour ?

A bunch of changesets

## When does this occur ?

all the time

## How do we replicate the issue ?

1. Create a new filter for Washington State 
2. open the new RSS feed in an RSS Reader
3.
4.

## Please tell us about your environment:

Using the latest Chrome browser with Nextcloud RSS news reader

**Comment by emersonveenstra** [comment] 2024-02-22 13:48
Duplicate of https://github.com/OSMCha/osmcha-frontend/issues/707

**Comment by willemarcel** [comment] 2024-03-01 03:10
It's now fixed.

**Closed by willemarcel** 2024-03-01 03:10 UTC
