### ISSUE TITLE
alert: "Changeset: ######### Map failed."

### ISSUE THREAD

**Issue by rkiddy** [OSMCha/osmcha-frontend#740] opened 2024-06-30 18:37 UTC
Have not come to osmcha for a while. Clicked on first change in the list. Got an alert. Ouch. :--)

Changeset 153380982

See snap.
![Screenshot from 2024-06-30 11-33-17](https://github.com/OSMCha/osmcha-frontend/assets/691368/6ef147d7-ea08-4ebb-9e87-667bde8dd841)

**Comment by rkiddy** [comment] 2024-06-30 18:38
And the "Retry" button does not stop the error.

**Comment by FransS1945** [comment] 2024-08-08 09:55
Same issue here. 
Check this link

https://osmcha.org/changesets/154919969
![image](https://github.com/user-attachments/assets/91a263c8-a9f6-435d-9ea8-c54373197135)

**Comment by batpad** [comment] 2024-08-08 10:12
Hmm @willemarcel @sunu - it seems to me like requests to the s3 bucket for real-changesets are failing, for example a changeset from a day ago: https://real-changesets.s3.us-west-2.amazonaws.com/154916228.json

This is causing all changeset queries to fallback to Overpass and making things slow / throwing occasional errors. Or at least, I **think** that's what's going on?

Can we try and take a look at the real-changesets pipeline and see if we can figure out why either the real changeset JSON is not making it to s3, or .. ?

**Comment by willemarcel** [comment] 2024-08-08 13:35
@batpad Our requests to osm servers were blocked yesterday for some hours (#742). That changeset was not ingested in the database, but I'm backfilling it now.

**Comment by literannn** [comment] 2024-08-26 07:29
I have the same error on ALL changesets since yesterday ^((

**Comment by tastrax** [comment] 2024-08-26 08:25
Likewise - every changeset errors out for me

![image](https://github.com/user-attachments/assets/423cb15b-4a16-446f-a0f6-1d6cc1ed85a0)

![image](https://github.com/user-attachments/assets/728abed5-a994-422c-ab9b-75258dda7d75)

**Comment by abdullahO2** [comment] 2024-08-26 09:00
same here:
Changeset:155770447 Map failed
**r.elements is undefined**
![image](https://github.com/user-attachments/assets/3159e2d5-d1a1-4fff-857e-40e327f72b9f)

**Comment by CAM-Gerlach** [comment] 2024-08-26 19:37
I can also consistently reproduce the issue for the past couple days, tested on many different changesets (mine, custom filters, global, direct links, etc), tested in regular and safe + Incognito mode on both Firefox and Chrome (Windows), logging out and back in again, clearing cache, etc. Additionally, I have not updated my OS, browsers, extensions or settings between when it worked and when it didn't (nor even restarted my machine).

![image](https://github.com/user-attachments/assets/3d40103d-12e0-4072-b76b-150842fe8368)

Here's the web console output, which appears to be behind the failing calls on the frontend given the direct link to the error message output.

```log
155799022:1 -1

beacon.min.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
console.js:35 Changeset:155799022 Map failed: Cannot read properties of undefined (reading '0')
    at https://osmcha.org/static/js/3.27dd8914.chunk.js:2:220118
e.<computed> @ console.js:35

155799022:1 Access to fetch at 'https://rksbsqdel4.execute-api.us-east-1.amazonaws.com/testing?action=names&id=19254040' from origin 'https://osmcha.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

rksbsqdel4.execute-api.us-east-1.amazonaws.com/testing?action=names&id=19254040:1          Failed to load resource: net::ERR_FAILED

console.js:35 TypeError: Failed to fetch
    at raven.js:1474:16
    at Rs (whosthat.js:5:10)
    at index.js:290:7
    at a._initFetching (fetch_data_enhancer.js:45:26)
    at y (index.js:160:19)
    at k (index.js:207:14)
    at w (index.js:195:14)
    at o (raven.js:376:21)
e.<computed> @ console.js:35

console.js:35 Changeset:155799022 Map failed: Cannot read properties of undefined (reading '0')
    at https://osmcha.org/static/js/3.27dd8914.chunk.js:2:220118
e.<computed> @ console.js:35
```

**Comment by willemarcel** [comment] 2024-08-26 20:00
This issue is now fixed.

**Closed by willemarcel** 2024-08-26 20:00 UTC

**Comment by CAM-Gerlach** [comment] 2024-08-26 22:27
Can confirm per my testing. Thanks!
